package com.bsmart.application.backend.firmsweb.Entity.FirmsBackEndDbEntities.Enums;

public enum AccountSheetType {

    BALANCESHEET,
    INCOMESHEET,
    CASHFLOWSHEET,
    FUNDFLOWSHEET,
    VERTICALANALYSISBALANCESHEET,
    VERTICALANALYSISINCOMESHEET,
    HORIZONTALANALYSISBALANCESHEET,
    HORIZONTALANALYSISINCOMESHEET,
    RATIOSHEET

}

